# Generated by Django 5.2.2 on 2025-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_friendroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_code', models.IntegerField()),
            ],
        ),
    ]
