# Generated by Django 5.2.2 on 2025-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userplus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplus',
            name='hobby',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userplus',
            name='introduce',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
