# Generated by Django 5.2.2 on 2025-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userplus_hobby_userplus_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='request',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
